### ISSUE TITLE
how to use http to access k8s api server？

### ISSUE THREAD

**Issue by TonyCMCC** [projectcalico/kube-controllers#291]
how to use http to access k8s api server？
logs information ：
E0905 08:51:51.786844       1 reflector.go:205] github.com/projectcalico/kube-controllers/pkg/controllers/node/node_controller.go:156: Failed to list *v1.Node: Get https://192.195.253.8:8080/api/v1/nodes?resourceVersion=0: http: server gave HTTP response to HTTPS client
E0905 08:51:52.436053       1 reflector.go:205] github.com/projectcalico/kube-controllers/pkg/controllers/networkpolicy/policy_controller.go:147: Failed to list *v1beta1.NetworkPolicy: Get https://192.195.253.8:8080/apis/extensions/v1beta1/networkpolicies?resourceVersion=0: http: server gave HTTP response to HTTPS client

**Comment by caseydavenport** [comment]
You'll need to provide the controller with a valid kubeconfig file for your environment - by default it will try to use https.

I'd strongly recommend configuring your apiserver to use https, rather than to modify the controller's configuration to use http. 

A bit more info here: https://docs.projectcalico.org/v3.2/reference/kube-controllers/configuration
